/LV/scale_truck_control_node:
  ros__parameters:    
    subscribers/camera_reading/topic: /usb_cam/image_raw
    subscribers/camera_reading/queue_size: 1
    subscribers/obstacle_reading/topic: /raw_obstacles
    subscribers/obstacle_reading/queue_size: 100
    subscribers/lrc_to_xavier/topic: lrc2xav_msg
    subscribers/lrc_to_xavier/queue_size: 1

    publishers/xavier_to_lrc/topic: xav2lrc_msg
    publishers/xavier_to_lrc/queue_size: 1

    params/LdOffset: 0.0
    params/LdOffset2: 0.0
    params/Lw: 0.3400000035762787
    params/fv_max_vel: 0.800000011920929
    params/fv_stop_dist: 0.5
    params/index: 0
    params/lv_stop_dist: 0.5
    params/rcm_dist: 0.800000011920929
    params/rcm_vel: 0.6000000238418579
    params/ref_vel: 0.0
    params/safety_dist: 1.5
    params/safety_vel: 0.30000001192092896
    params/target_dist: 0.800000011920929
    params/target_vel: 0.5

    image_view/enable_console_output: true
    image_view/enable_opencv: true
    image_view/wait_key_delay: 2
