/**/LaneDetector:
  ros__parameters:
    subscribers/image_to_lane/topic: usb_cam/image_raw

    image_view/enable_opencv: true
    rear_image_view/enable_opencv: false 
    image_view/wait_key_delay: 1

    image_view/enable_adthreshold: true
    threshold/box_size: 51   # 51 71 
    threshold/box_offset: 50 # 50 43
    ROI/threshold: 128

    params/angle_degree: 0.0
    params/Kp_d: 2.0
    params/Ki_d: 0.2

    Calibration/f_matrix/a: 325.45672218217680
    Calibration/f_matrix/b: 0.
    Calibration/f_matrix/c: 320.
    Calibration/f_matrix/d: 0.
    Calibration/f_matrix/e: 325.45672218217680
    Calibration/f_matrix/f: 240. 
    Calibration/f_matrix/g: 0.
    Calibration/f_matrix/h: 0.
    Calibration/f_matrix/i: 1.

    Calibration/f_dist_coef/a: -0.35139098089507653
    Calibration/f_dist_coef/b: 0.15748570446604712
    Calibration/f_dist_coef/c: 0.
    Calibration/f_dist_coef/d: 0.
    Calibration/f_dist_coef/e: -0.037408338000060472

    ROI/dynamic_roi: true
    ROI/canny/thresh1: 100
    ROI/canny/thresh2: 200

    ROI/width: 640
    ROI/height: 480

    ROI/front_cam/top_gap: 0.41 
    ROI/front_cam/bot_gap: 0.17 
    ROI/front_cam/top_height: 0.99
    ROI/front_cam/bot_height: 0.47
    ROI/front_cam/extra_f: 12.00
    ROI/front_cam/extra_b: 18.00
    ROI/front_cam/extra_up: 140
    ROI/front_cam/extra_down: 180
    
    ROI/wide_right/width: 640
    ROI/wide_right/height: 480
    ROI/wide_right/top_gap: 0.40 # 0.28
    ROI/wide_right/bot_gap: 0.16 # 0.0
    ROI/wide_right/top_height: 0.99
    ROI/wide_right/bot_height: 0.485
    ROI/wide_right/extra_f: 8.00 # 0
    ROI/wide_right/extra_b: 8.00 # 0
    ROI/wide_right/extra_up: 180
    ROI/wide_right/extra_down: 220

    ROI/wide_left/width: 640
    ROI/wide_left/height: 480
    ROI/wide_left/top_gap: 0.40 # 0.28
    ROI/wide_left/bot_gap: 0.16 # 0.0
    ROI/wide_left/top_height: 0.99
    ROI/wide_left/bot_height: 0.485
    ROI/wide_left/extra_f: 8.00 # 0
    ROI/wide_left/extra_b: 8.00 # 0
    ROI/wide_left/extra_up: 180
    ROI/wide_left/extra_down: 220

    crop/x: 100
    crop/y: 0
    crop/width: 440
    crop/height: 380

    params/K: 0.15
    params/a/a: 0.
    params/a/b: -0.22027
    params/a/c: 0.847
    params/a/d: -1.1516
    params/a/e: 0.60261

    params/b/a: 0.
    params/b/b: -1.3982
    params/b/c: 4.1189
    params/b/d: -4.0208
    params/b/e: 1.41

    LaneDetector/eL_height: 0.2
    LaneDetector/e1_height: 1.2563
    LaneDetector/trust_height: 0.6667
    LaneDetector/lp: 609.3
    LaneDetector/steer_angle: 0.0

