tcp_ip:
  ip_addr_server: "tcp://*"
  ip_addr_client: "tcp://192.168.0.30"
  interface_name: "wlan0"
  req_port: "5555"
  rep_port: "8888"
  zipcode: "00001"

tcpimg_ip:
  ip_addr_server: "tcp://*"
  ip_addr_client: "tcp://192.168.0.12"
  req_port: ""
  rep_port: "50000"

udp_ip:
  ip_addr: "udp://239.255.255.251"
  port: "9091"
  send_group: "FV"
  recv_group: "LV"

socket:
  rad_flag: false
  dsh_flag: false
  req_flag: false
  rep_flag: true
  req_img_flag: false
  rep_img_flag: true

params:
  index: 1
  target_vel: 0.00
  safety_vel: 0.45
  fv_max_vel: 1.20
  lv_stop_dist: 0.5
  fv_stop_dist: 0.4
  safety_dist: 0.8
  target_dist: 0.8
  angle_degree: 0.0
  Kp_d: 2.0
  Kd_d: 0.4
  K: 0.15
  a:
    a: 0.
    b: -0.22027
    c: 0.847
    d: -1.1516
    e: 0.60261
  b:
    a: 0.
    b: -1.3982
    c: 4.1189
    d: -4.0208
    e: 1.41
  K3: 0.20 # 0.25 
  K4: 0.30 # 0.51
  Lw: 0.34
  LdOffset: 0 # -0.37 35 ~ 38-0.5
  LdOffset2: -0.5 # -0.5
  
Calibration:
  f_matrix:
    a: 325.45672218217680
    b: 0.
    c: 320. 
    d: 0. 
    e: 325.45672218217680
    f: 240. 
    g: 0. 
    h: 0. 
    i: 1.
  f_dist_coef:
    a: -0.35139098089507653
    b: 0.15748570446604712
    c: 0.
    d: 0. 
    e: -0.037408338000060472
  r_matrix:
    a: 326.31389227574556
    b: 0.
    c: 320. 
    d: 0. 
    e: 326.31389227574556
    f: 240. 
    g: 0. 
    h: 0. 
    i: 1.
  r_dist_coef:
    a: -0.33295846454356126
    b: 0.12386827336557986
    c: 0.
    d: 0. 
    e: -0.022565312043601477

ROI:
  front_cam:
    width: 640
    height: 480
    top_gap: 0.413
    bot_gap: 0.185
    top_height: 0.99
    bot_height: 0.485
    extra_f: 8.00
    extra_b: 8.00
    extra_up: 140
    extra_down: 180
  rear_cam:
    width: 640
    height: 480
    top_gap: 0.405
    bot_gap: 0.17
    top_height: 0.99
    bot_height: 0.47
    extra_f: 1
    extra_b: 10
    extra_up: 140
    extra_down: 180

rear_camera_usage:
  use: false
