/**/LaneDetector:
  ros__parameters:
    subscribers/image_to_lane/topic: usb_cam/image_raw
    subscribers/image_to_lane/queue_size: 1
    subscribers/rearImage_to_lane/topic: null
    subscribers/rearImage_to_lane/queue_size: 1
    subscribers/xavier_to_lane/topic: xav2lane_msg
    subscribers/xavier_to_lane/queue_size: 1

    publishers/lane_to_xavier/topic: lane2xav_msg
    publishers/lane_to_xavier/queue_size: 1

    image_view/enable_opencv: true
    image_view/wait_key_delay: 1

    image_view/enable_adthreshold: true
    threshold/box_size: 51   # 51 71 
    threshold/box_offset: 50 # 50 43
    ROI/threshold: 200

    params/angle_degree: 0.0
    params/Kp_d: 2.0
    params/Ki_d: 0.2

    Calibration/f_matrix/a: 332.03782768352386
    Calibration/f_matrix/b: 0.
    Calibration/f_matrix/c: 320.
    Calibration/f_matrix/d: 0.
    Calibration/f_matrix/e: 332.03782768352386
    Calibration/f_matrix/f: 240. 
    Calibration/f_matrix/g: 0.
    Calibration/f_matrix/h: 0.
    Calibration/f_matrix/i: 1.

    Calibration/f_dist_coef/a: -0.33140950145477255
    Calibration/f_dist_coef/b: 0.12372697252401374
    Calibration/f_dist_coef/c: 0.
    Calibration/f_dist_coef/d: 0.
    Calibration/f_dist_coef/e: -0.022529125535951176

    ROI/dynamic_roi: true
    ROI/canny/thresh1: 100
    ROI/canny/thresh2: 200

    ROI/front_cam/width: 640
    ROI/front_cam/height: 480
    ROI/front_cam/top_gap: 0.41 # 0.35 
    ROI/front_cam/bot_gap: 0.17 # 0.10 
    ROI/front_cam/top_height: 0.99
    ROI/front_cam/bot_height: 0.47 
    ROI/front_cam/extra_f: 16.0 # 30.0 
    ROI/front_cam/extra_b: 8.0  # 30.0
    ROI/front_cam/extra_up: 140
    ROI/front_cam/extra_down: 180

    ROI/wide_right/width: 640
    ROI/wide_right/height: 480
    ROI/wide_right/top_gap: 0.40 # 0.28
    ROI/wide_right/bot_gap: 0.16 # 0.0
    ROI/wide_right/top_height: 0.99
    ROI/wide_right/bot_height: 0.47
    ROI/wide_right/extra_f: 16.00 # 0
    ROI/wide_right/extra_b: 8.00 # 0
    ROI/wide_right/extra_up: 180
    ROI/wide_right/extra_down: 220

    ROI/wide_left/width: 640
    ROI/wide_left/height: 480
    ROI/wide_left/top_gap: 0.40 # 0.28
    ROI/wide_left/bot_gap: 0.16 # 0.0
    ROI/wide_left/top_height: 0.99
    ROI/wide_left/bot_height: 0.47
    ROI/wide_left/extra_f: 16.00 # 0
    ROI/wide_left/extra_b: 8.00 # 0
    ROI/wide_left/extra_up: 180
    ROI/wide_left/extra_down: 220

    crop/x: 100
    crop/y: 0
    crop/width: 440
    crop/height: 380

    params/K: 0.15
    params/K3: 0.15 # e1 
    params/K4: 0.15 # eL 
    
    params/a/a: 15.382
    params/a/b: -57.657
    params/a/c: 79.912
    params/a/d: -48.716
    params/a/e: 11.19

    params/b/a: 9.4969
    params/b/b: -37.445
    params/b/c: 54.573
    params/b/d: -34.897
    params/b/e: 8.4135

    LaneDetector/eL_height: 0.2
    LaneDetector/e1_height: 1.2563
    LaneDetector/trust_height: 0.6667
    LaneDetector/lp: 609.3 
    LaneDetector/steer_angle: 0.0

/**/RearLaneDetector:
  ros__parameters:
    subscribers/image_to_lane/topic: null
    subscribers/image_to_lane/queue_size: 1
    subscribers/rearImage_to_lane/topic: rear_cam/image_raw
    subscribers/rearImage_to_lane/queue_size: 1

    publishers/lane_to_xavier/topic: rear2xav_msg
    publishers/lane_to_xavier/queue_size: 1

    image_view/enable_opencv: true
    image_view/wait_key_delay: 1

    image_view/enable_adthreshold: true
    threshold/box_size:   51 # 51 71 
    threshold/box_offset: 50 # 50 43
    ROI/threshold: 128

    Calibration/r_matrix/a: 3.2943729391263065e+02
    Calibration/r_matrix/b: 0.
    Calibration/r_matrix/c: 320.
    Calibration/r_matrix/d: 0.
    Calibration/r_matrix/e: 3.2943729391263065e+02
    Calibration/r_matrix/f: 240.
    Calibration/r_matrix/g: 0.
    Calibration/r_matrix/h: 0.
    Calibration/r_matrix/i: 1.

    Calibration/r_dist_coef/a: -3.4378345298743745e-01
    Calibration/r_dist_coef/b: 1.4967084861572430e-01
    Calibration/r_dist_coef/c: 0.
    Calibration/r_dist_coef/d: 0.
    Calibration/r_dist_coef/e: -4.0688891786494791e-02

    ROI/rear_cam/top_gap: 0.405
    ROI/rear_cam/bot_gap: 0.17
    ROI/rear_cam/top_height: 0.99
    ROI/rear_cam/bot_height: 0.47
    ROI/rear_cam/extra_f: 1.
    ROI/rear_cam/extra_b: 10.
    ROI/rear_cam/extra_up: 140
    ROI/rear_cam/extra_down: 180

