/**/LRC:
  ros__parameters:
    LrcSub/xavier_to_lrc/topic: xav2lrc_msg
    LrcSub/xavier_to_lrc/queue_size: 1
    LrcSub/ocr_to_lrc/topic: ocr2lrc_msg
    LrcSub/ocr_to_lrc/queue_size: 1
    LrcSub/lv_to_fv/topic: /lv2fv_msg
    LrcSub/lv_to_fv/queue_size: 1

    LrcPub/lrc_to_xavier/topic: lrc2xav_msg
    LrcPub/lrc_to_xavier/queue_size: 1
    LrcPub/lrc_to_ocr/topic: lrc2ocr_msg
    LrcPub/lrc_to_ocr/queue_size: 1
    LrcPub/lv_to_fv/topic: /lv2fv_msg
    LrcPub/lv_to_fv/queue_size: 1

    LrcParams/lrc_index: 10
    LrcParams/lrc_log_path: /home/avees/uros_ws/logfiles/
    LrcParams/epsilon: 3.0
    LrcParams/lu_ob_A: 0.6817
    LrcParams/lu_ob_B: 0.3183
    LrcParams/lu_ob_L: 0.1183
    LrcParams/enable_console_output: true
