/**/LRC:
  ros__parameters:
    LrcSubPub/xavier_to_lrc/topic: xav2lrc_msg
    LrcSubPub/xavier_to_lrc/queue_size: 1
    LrcSubPub/ocr_to_lrc/topic: ocr2lrc_msg
    LrcSubPub/ocr_to_lrc/queue_size: 1
    LrcSubPub/lrc_to_xavier/topic: lrc2xav_msg
    LrcSubPub/lrc_to_xavier/queue_size: 1
    LrcSubPub/lrc_to_ocr/topic: lrc2ocr_msg
    LrcSubPub/lrc_to_ocr/queue_size: 1

    LrcParams/lrc_index: 11
    LrcParams/lrc_log_path: /home/avees/uros_ws/logfiles/
    LrcParams/epsilon: 3.0
    LrcParams/lu_ob_A: 0.6817
    LrcParams/lu_ob_B: 0.3183
    LrcParams/lu_ob_L: 0.1183
    LrcParams/enable_console_output: false
