/**/LaneDetector:
  ros__parameters:
    subscribers/image_to_lane/topic: usb_cam/image_raw
    subscribers/image_to_lane/queue_size: 1
    subscribers/rearImage_to_lane/topic: null
    subscribers/rearImage_to_lane/queue_size: 1
    subscribers/xavier_to_lane/topic: xav2lane_msg
    subscribers/xavier_to_lane/queue_size: 1

    publishers/lane_to_xavier/topic: lane2xav_msg
    publishers/lane_to_xavier/queue_size: 1

    image_view/enable_opencv: false
    image_view/wait_key_delay: 1

    params/angle_degree: 0.0
    params/Kp_d: 2.0
    params/Ki_d: 0.2

    Calibration/f_matrix/a: 329.10805843346054
    Calibration/f_matrix/b: 0.
    Calibration/f_matrix/c: 320.
    Calibration/f_matrix/d: 0.
    Calibration/f_matrix/e: 329.10805843346054
    Calibration/f_matrix/f: 240. 
    Calibration/f_matrix/g: 0.
    Calibration/f_matrix/h: 0.
    Calibration/f_matrix/i: 1.

    Calibration/f_dist_coef/a: -0.34335984453339752
    Calibration/f_dist_coef/b: 0.14676511736197059
    Calibration/f_dist_coef/c: 0.
    Calibration/f_dist_coef/d: 0.
    Calibration/f_dist_coef/e: -0.032260115806245951

    ROI/dynamic_roi: true
    ROI/width: 640
    ROI/height: 480

    ROI/front_cam/width: 640
    ROI/front_cam/height: 480
    ROI/front_cam/top_gap: 0.416 # 0.28
    ROI/front_cam/bot_gap: 0.185 # 0.0
    ROI/front_cam/top_height: 0.99
    ROI/front_cam/bot_height: 0.47
    ROI/front_cam/extra_f: 0.00 # 0
    ROI/front_cam/extra_b: -6.00 # 0
    ROI/front_cam/extra_up: 140
    ROI/front_cam/extra_down: 180

    ROI/wide_right/width: 640
    ROI/wide_right/height: 480
    ROI/wide_right/top_gap: 0.40 # 0.28
    ROI/wide_right/bot_gap: 0.16 # 0.0
    ROI/wide_right/top_height: 0.99
    ROI/wide_right/bot_height: 0.47
    ROI/wide_right/extra_f: 0.00 # 0
    ROI/wide_right/extra_b: 0.00 # 0
    ROI/wide_right/extra_up: 180
    ROI/wide_right/extra_down: 220

    ROI/wide_left/width: 640
    ROI/wide_left/height: 480
    ROI/wide_left/top_gap: 0.40 # 0.28
    ROI/wide_left/bot_gap: 0.16 # 0.0
    ROI/wide_left/top_height: 0.99
    ROI/wide_left/bot_height: 0.47
    ROI/wide_left/extra_f: 0.00 # 0
    ROI/wide_left/extra_b: 0.00 # 0
    ROI/wide_left/extra_up: 180
    ROI/wide_left/extra_down: 220

    threshold/box_size:   51 # 51 71 
    threshold/box_offset: 50 # 50 43

    params/K: 0.15  #vel 0.6,   0.8,  1.0  
    params/K3: 0.07 # e1 0.13,  0.075, 0.07   키우면 각도 커진다, 고개 오실레이션 -> 낮춰 
    
    params/K4: 0.14 # eL 0.173, 0.16, 0.14   키우면 각도 작아져, 낮추면 오실? 각도 작아? 

    params/a/a: 0.
    params/a/b: -0.37169
    params/a/c: 1.2602
    params/a/d: -1.5161
    params/a/e: 0.70696

    params/b/a: 0.
    params/b/b: -1.7536
    params/b/c: 5.0931
    params/b/d: -4.9047
    params/b/e: 1.6722

    LaneDetector/eL_height: 0.2
    LaneDetector/e1_height: 1.1852 # 1.2563 1.1852
    LaneDetector/trust_height: 0.6667
    LaneDetector/lp: 609.3 # 609.3 472.9
    LaneDetector/steer_angle: 0.0

/**/RearLaneDetector:
  ros__parameters:
    subscribers/image_to_lane/topic: null
    subscribers/image_to_lane/queue_size: 1
    subscribers/rearImage_to_lane/topic: rear_cam/image_raw
    subscribers/rearImage_to_lane/queue_size: 1

    publishers/lane_to_xavier/topic: rear2xav_msg
    publishers/lane_to_xavier/queue_size: 1

    image_view/enable_opencv: false
    image_view/wait_key_delay: 1
    image_view/TEST: false

    threshold/box_size:   51 # 51 71 
    threshold/box_offset: 50 # 50 43

    Calibration/r_matrix/a: 326.31389227574556
    Calibration/r_matrix/b: 0.
    Calibration/r_matrix/c: 320.
    Calibration/r_matrix/d: 0.
    Calibration/r_matrix/e: 326.31389227574556
    Calibration/r_matrix/f: 240.
    Calibration/r_matrix/g: 0.
    Calibration/r_matrix/h: 0.
    Calibration/r_matrix/i: 1.

    Calibration/r_dist_coef/a: -0.33295846454356126
    Calibration/r_dist_coef/b: 0.12386827336557986
    Calibration/r_dist_coef/c: 0.
    Calibration/r_dist_coef/d: 0.
    Calibration/r_dist_coef/e: -0.022565312043601477

    ROI/rear_cam/top_gap: 0.405
    ROI/rear_cam/bot_gap: 0.17
    ROI/rear_cam/top_height: 0.99
    ROI/rear_cam/bot_height: 0.47
    ROI/rear_cam/extra_f: 1.
    ROI/rear_cam/extra_b: 10.
    ROI/rear_cam/extra_up: 140
    ROI/rear_cam/extra_down: 180

    ROI/test/width: 640 
    ROI/test/height: 480 
    ROI/test/top_gap: 0.45  
    ROI/test/bot_gap: 0.175  
    ROI/test/top_height: 0.99 
    ROI/test/bot_height: 0.41 
    ROI/test/extra_f: 12.00 #48.00 #-28.00 
    ROI/test/extra_b: 10.00 #360.00 #-299.00 
    ROI/test/extra_up: 220  #240  # 140 
    ROI/test/extra_down: 200 #100 #280  # 180 
