/**:
    ros__parameters:
      video_device: "/dev/video4"
      framerate: 30.0
      io_method: "mmap"
      frame_id: "rear_cam"
      pixel_format: "yuyv"  # see usb_cam/supported_formats for list of supported formats
      image_width: 640
      image_height: 480
      camera_name: "rear_cam"
